name: Build macOS Desktop App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Force Executable Permissions on All Workspace Files
        run: chmod -R +x .

      - name: Prepare stlite Artifacts
        run: npx dump-stlite-desktop-artifacts

      - name: Build Electron App for Mac
        run: npx electron-builder --mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Mac App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-Desktop-App
          path: dist/*.dmg
          retention-days: 7